PACKAGE_NAME="applesmc-als"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="applesmc-als"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver} KERNEL_DIR=/lib/modules/${kernelver}/build"
